name: 'Generate release notes'
description: 'Generate release notes'
inputs:
  auth_token:
    description: 'The token used to authenticate to GitHub.'
    required: true
  output:
    description: 'The output file to save the release notes to.'
    required: true
  build_description:
    description: 'Build description.'
    required: true
  last_release_date:
    description: 'Last release date in ISO 8601 format.'
    required: true
  branch_name:
    description: 'The branch to generate release notes for.'
    required: true
  additional_branch:
    description: "Include PRs from an additional branch"
    required: false

runs:
  using: 'node16'
  main: 'index.js'
