//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Diagnostics.Monitoring.StartupHook.ParameterCapturing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ParameterCapturingStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParameterCapturingStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Diagnostics.Monitoring.StartupHook.ParameterCapturing.ParameterCapturin" +
                            "gStrings", typeof(ParameterCapturingStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following method descriptions are not allowed: {0}.
        /// </summary>
        internal static string DeniedMethodsFormatString {
            get {
                return ResourceManager.GetString("DeniedMethodsFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; is unsupported, it does not have a function id..
        /// </summary>
        internal static string ErrorMessage_FunctionDoesNotHaveIdFormatString {
            get {
                return ResourceManager.GetString("ErrorMessage_FunctionDoesNotHaveIdFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatch probe state. Expected &apos;{0}&apos;, was &apos;{1}&apos;..
        /// </summary>
        internal static string ErrorMessage_ProbeStateMismatchFormatString {
            get {
                return ResourceManager.GetString("ErrorMessage_ProbeStateMismatchFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided signature blob must be for a method..
        /// </summary>
        internal static string ErrorMessage_SignatureIsNotForAMethod {
            get {
                return ResourceManager.GetString("ErrorMessage_SignatureIsNotForAMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter capturing encountered an internal error when processing &apos;{0}!{1}.{2}&apos;, stopping..
        /// </summary>
        internal static string StoppingParameterCapturingDueToProbeFault {
            get {
                return ResourceManager.GetString("StoppingParameterCapturingDueToProbeFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many requests.
        /// </summary>
        internal static string TooManyRequestsErrorMessage {
            get {
                return ResourceManager.GetString("TooManyRequestsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve one or more method descriptions: {0}.
        /// </summary>
        internal static string UnresolvedMethodsFormatString {
            get {
                return ResourceManager.GetString("UnresolvedMethodsFormatString", resourceCulture);
            }
        }
    }
}
