apiVersion: apps/v1
kind: Deployment
metadata:
  name: akstest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akstest
  template:
    metadata:
      labels:
        app: akstest
    spec:
      restartPolicy: Always
      securityContext:
        fsGroup: 1654 # Default APP_ID for the aspnetapp image
      containers:
      - name: publishedapp
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_URLS
          value: http://+:8080
        - name: DOTNET_DiagnosticPorts
          value: /diag/port.sock
        volumeMounts:
        - mountPath: /diag
          name: diagvol
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
      - name: monitor
        image: mcr.microsoft.com/dotnet/monitor:8
        imagePullPolicy: Always
        env:
        - name: DotnetMonitor_DiagnosticPort__ConnectionMode
          value: 'Listen'
        - name: DotnetMonitor_DiagnosticPort__EndpointName
          value: /diag/port.sock
        # ALWAYS use the HTTPS form of the URL for deployments in production; the removal of HTTPS is done for
        # demonstration purposes only in this example. Please continue reading after this example for further details.
        - name: DotnetMonitor_Urls
          value: 'http://localhost:52323'
        - name: DotnetMonitor_Storage__DumpTempFolder
          value: /diag/dumps
        - name: DotnetMonitor_Logging__Console__FormatterName
          value: simple
        volumeMounts:
        - mountPath: /diag
          name: diagvol
        - mountPath: /etc/dotnet-monitor
          name: dotnet-monitor-config
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
      volumes:
      - name: diagvol
        emptyDir: {}
      - name: dotnet-monitor-config
        projected:
          defaultMode: 400
          sources:
            - configMap:
                name: dotnet-monitor-egress
                optional: false
            - configMap:
                name: dotnet-monitor-triggers
                optional: false
            - secret:
                name: apikey
