trigger: none

pr:
  autoCancel: true
  branches:
    include:
    - main
    - release/*
    - internal/release/*
    - feature/*

variables:
- name: _TeamName
  value: DotNetCore

- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  # DotNet-Diagnostics-SDL-Params provides Tsa* variables for SDL checks.
  - group: DotNet-Diagnostics-SDL-Params

stages:
- stage: Build
  jobs:
  - template: /eng/build.yml
    parameters:
      name: Windows_x64_Debug
      displayName: Windows x64 Debug
      osGroup: Windows
      configuration: Debug
  - template: /eng/build.yml
    parameters:
      name: Windows_x64_Release
      displayName: Windows x64 Release
      osGroup: Windows
      configuration: Release
      signAndPublishArtifacts: true
  - template: /eng/build.yml
    parameters:
      name: Windows_x86_Release
      displayName: Windows x86 Release
      osGroup: Windows
      configuration: Release
      architecture: x86
  - template: /eng/build.yml
    parameters:
      name: CentOS_x64_Debug
      displayName: CentOS x64 Debug
      osGroup: Linux
      configuration: Debug
  - template: /eng/build.yml
    parameters:
      name: CentOS_x64_Release
      displayName: CentOS x64 Release
      osGroup: Linux
      configuration: Release
  - template: /eng/build.yml
    parameters:
      name: Alpine_x64_Debug
      displayName: Alpine x64 Debug
      osGroup: Linux_Musl
      configuration: Debug
  - template: /eng/build.yml
    parameters:
      name: Alpine_x64_Release
      displayName: Alpine x64 Release
      osGroup: Linux_Musl
      configuration: Release
  - template: /eng/build.yml
    parameters:
      name: MacOS_x64_Debug
      displayName: MacOS x64 Debug
      osGroup: MacOS
      configuration: Debug
  - template: /eng/build.yml
    parameters:
      name: MacOS_x64_Release
      displayName: MacOS x64 Release
      osGroup: MacOS
      configuration: Release
  # This registers the build with BAR.
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - template: /eng/common/templates/job/publish-build-assets.yml
      parameters:
        configuration: Release
        dependsOn:
        - Windows_x64_Debug
        - Windows_x64_Release
        - Windows_x86_Release
        - CentOS_x64_Debug
        - CentOS_x64_Release
        - Alpine_x64_Debug
        - Alpine_x64_Release
        - MacOS_x64_Debug
        - MacOS_x64_Release
        publishUsingPipelines: true
        pool:
          name: NetCore1ESPool-Internal
          demands: ImageOverride -equals build.windows.10.amd64.vs2017
# These are the stages that perform validation of several SDL requirements and publish the bits required to the designated feed.
- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - template: /eng/common/templates/post-build/post-build.yml
    parameters:
      # This is to enable SDL runs part of Post-Build Validation Stage.
      # as well as NuGet, SourceLink, and signing validation.
      # The variables get imported from group dotnet-diagnostics-sdl-params
      publishingInfraVersion: 3
      # Only enable SourceLink validation for branches that are mirrored.
      # Otherwise, the validation job will timeout the build waiting for source version to exist
      # in GitHub, which will not occur for branches that only exist in the internal project.
      ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')) }}:
        enableSourceLinkValidation: true
      ${{ else }}:
        enableSourceLinkValidation: false
      enableSigningValidation: true
      enableSymbolValidation: false
      enableNugetValidation: true
      publishInstallersAndChecksums: true
      SDLValidationParameters:
        enable: true
        continueOnError: true
        params: ' -SourceToolsList @("policheck","credscan")
        -TsaInstanceURL $(_TsaInstanceURL)
        -TsaProjectName $(_TsaProjectName)
        -TsaNotificationEmail $(_TsaNotificationEmail)
        -TsaCodebaseAdmin $(_TsaCodebaseAdmin)
        -TsaBugAreaPath $(_TsaBugAreaPath)
        -TsaIterationPath $(_TsaIterationPath)
        -TsaRepositoryName "dotnet-monitor"
        -TsaCodebaseName "dotnet-monitor"
        -TsaPublish $True'
        artifactNames:
        - 'PackageArtifacts'
# This sets up the bits to do a Release.
- template: /eng/PrepareRelease.yml
