trigger: none

pr:
  autoCancel: true
  branches:
    include:
    - main
    - release/*
    - internal/release/*
    - feature/*

variables:
  - name: _TeamName
    value: DotNetCore
  
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    # DotNet-Diagnostics-SDL-Params provides Tsa* variables for SDL checks.
    - group: DotNet-Diagnostics-SDL-Params

stages:
  - stage: Build
    jobs:
    - template: /eng/build.yml
      parameters:
        name: WindowsDebug
        displayName: Windows Debug
        osGroup: Windows
        configuration: Debug
    - template: /eng/build.yml
      parameters:
        name: WindowsRelease
        displayName: Windows Release
        osGroup: Windows
        configuration: Release
        signAndPublishArtifacts: true
    - template: /eng/build.yml
      parameters:
        name: CentOSDebug
        displayName: CentOS Debug
        osGroup: Linux
        configuration: Debug
    - template: /eng/build.yml
      parameters:
        name: CentOSRelease
        displayName: CentOS Release
        osGroup: Linux
        configuration: Release
    - template: /eng/build.yml
      parameters:
        name: AlpineDebug
        displayName: Alpine Debug
        osGroup: Linux_Musl
        configuration: Debug
    - template: /eng/build.yml
      parameters:
        name: AlpineRelease
        displayName: Alpine Release
        osGroup: Linux_Musl
        configuration: Release
    - template: /eng/build.yml
      parameters:
        name: MacOSDebug
        displayName: MacOS Debug
        osGroup: MacOS
        configuration: Debug
    - template: /eng/build.yml
      parameters:
        name: MacOSRelease
        displayName: MacOS Release
        osGroup: MacOS
        configuration: Release
    # This registers the build with BAR.
    - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
      - template: /eng/common/templates/job/publish-build-assets.yml
        parameters:
          configuration: Release
          dependsOn:
          - WindowsDebug
          - WindowsRelease
          - CentOSDebug
          - CentOSRelease
          - AlpineDebug
          - AlpineRelease
          - MacOSDebug
          - MacOSRelease
          publishUsingPipelines: true
          pool:
            name: NetCore1ESPool-Internal
            demands: ImageOverride -equals build.windows.10.amd64.vs2017
  # These are the stages that perform validation of several SDL requirements and publish the bits required to the designated feed.
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - template: /eng/common/templates/post-build/post-build.yml
      parameters:
        # This is to enable SDL runs part of Post-Build Validation Stage.
        # as well as NuGet, SourceLink, and signing validation.
        # The variables get imported from group dotnet-diagnostics-sdl-params
        publishingInfraVersion: 3
        enableSourceLinkValidation: true
        enableSigningValidation: true
        enableSymbolValidation: false
        enableNugetValidation: true
        publishInstallersAndChecksums: true
        SDLValidationParameters:
          enable: true
          continueOnError: true
          params: ' -SourceToolsList @("policheck","credscan")
          -TsaInstanceURL $(_TsaInstanceURL)
          -TsaProjectName $(_TsaProjectName)
          -TsaNotificationEmail $(_TsaNotificationEmail)
          -TsaCodebaseAdmin $(_TsaCodebaseAdmin)
          -TsaBugAreaPath $(_TsaBugAreaPath)
          -TsaIterationPath $(_TsaIterationPath)
          -TsaRepositoryName "dotnet-monitor"
          -TsaCodebaseName "dotnet-monitor"
          -TsaPublish $True'
          artifactNames:
          - 'PackageArtifacts'
  # This sets up the bits to do a Release.
  - template: /eng/PrepareRelease.yml
