trigger: none

pr:
  autoCancel: true
  branches:
    include:
    - main
    - release/*
    - internal/release/*
    - feature/*
  paths:
    exclude:
    - .devcontainer
    - .github
    - .vscode
    - '**.md'

schedules:
- cron: 15 11 * * 6
  displayName: Weekly Full Test Run
  branches:
    include:
    - main
  always: true

parameters:
- name: TestGroup
  displayName: 'Test Group'
  type: string
  default: Default
  values:
  - Default
  - All
  - None
  - CI
  - PR

variables:
- name: _TeamName
  value: DotNetCore

- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  # DotNet-Diagnostics-SDL-Params provides Tsa* variables for SDL checks.
  - group: DotNet-Diagnostics-SDL-Params

stages:
- stage: Build
  displayName: Build and Test
  jobs:
  # Build and test binaries
  - template: /eng/build.yml
    parameters:
      name: Windows_x64_Debug
      displayName: Windows x64 Debug
      osGroup: Windows
      configuration: Debug
      testGroup: ${{ parameters.TestGroup }}
  - template: /eng/build.yml
    parameters:
      name: Windows_x64_Release
      displayName: Windows x64 Release
      osGroup: Windows
      configuration: Release
      publishArtifactsSubPaths:
      - source: 'bin'
      - source: 'obj'
      testGroup: ${{ parameters.TestGroup }}
  - template: /eng/build.yml
    parameters:
      name: Windows_x86_Release
      displayName: Windows x86 Release
      osGroup: Windows
      configuration: Release
      architecture: x86
      publishArtifactsSubPaths:
      - source: 'bin/Windows_NT.x86.Release'
      testGroup: ${{ parameters.TestGroup }}
  - ${{ if ne(variables['System.TeamProject'], 'public') }}:
    - template: /eng/build.yml
      parameters:
        name: Windows_arm64_Release
        displayName: Windows arm64 Release
        osGroup: Windows
        configuration: Release
        architecture: arm64
        publishArtifactsSubPaths:
        - source: 'bin/Windows_NT.arm64.Release'
        testGroup: None
  - template: /eng/build.yml
    parameters:
      name: Linux_x64_Debug
      displayName: Linux x64 Debug
      osGroup: Linux
      configuration: Debug
      testGroup: ${{ parameters.TestGroup }}
  - template: /eng/build.yml
    parameters:
      name: Linux_x64_Release
      displayName: Linux x64 Release
      osGroup: Linux
      configuration: Release
      publishArtifactsSubPaths:
      - source: 'bin/Linux.x64.Release'
      testGroup: ${{ parameters.TestGroup }}
  - ${{ if ne(variables['System.TeamProject'], 'public') }}:
    - template: /eng/build.yml
      parameters:
        name: Linux_arm64_Release
        displayName: Linux arm64 Release
        osGroup: Linux
        configuration: Release
        architecture: arm64
        publishArtifactsSubPaths:
        - source: 'bin/Linux.arm64.Release'
        testGroup: None
  - template: /eng/build.yml
    parameters:
      name: Linux_Musl_x64_Debug
      displayName: Linux Musl x64 Debug
      osGroup: Linux_Musl
      configuration: Debug
      testGroup: ${{ parameters.TestGroup }}
  - template: /eng/build.yml
    parameters:
      name: Linux_Musl_x64_Release
      displayName: Linux Musl x64 Release
      osGroup: Linux_Musl
      configuration: Release
      publishArtifactsSubPaths:
      - source: 'bin/Linux.x64.Release'
        target: 'bin/Linux-musl.x64.Release'
      testGroup: ${{ parameters.TestGroup }}
  - ${{ if ne(variables['System.TeamProject'], 'public') }}:
    - template: /eng/build.yml
      parameters:
        name: Linux_Musl_arm64_Release
        displayName: Linux Musl arm64 Release
        osGroup: Linux_Musl
        configuration: Release
        architecture: arm64
        publishArtifactsSubPaths:
        - source: 'bin/Linux.arm64.Release'
          target: 'bin/Linux-musl.arm64.Release'
        testGroup: None
  - template: /eng/build.yml
    parameters:
      name: MacOS_x64_Debug
      displayName: MacOS x64 Debug
      osGroup: MacOS
      configuration: Debug
      testGroup: ${{ parameters.TestGroup }}
  - template: /eng/build.yml
    parameters:
      name: MacOS_x64_Release
      displayName: MacOS x64 Release
      osGroup: MacOS
      configuration: Release
      publishArtifactsSubPaths:
      - source: 'bin/OSX.x64.Release'
      testGroup: ${{ parameters.TestGroup }}
  - ${{ if ne(variables['System.TeamProject'], 'public') }}:
    - template: /eng/build.yml
      parameters:
        name: MacOS_arm64_Release
        displayName: MacOS arm64 Release
        osGroup: MacOS
        configuration: Release
        architecture: arm64
        publishArtifactsSubPaths:
        - source: 'bin/OSX.arm64.Release'
        testGroup: None
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    # Pack, sign, and publish
    - template: /eng/common/templates/job/job.yml
      parameters:
        name: Pack_Sign
        displayName: Pack and Sign
        dependsOn:
        - Windows_x64_Release
        - Windows_x86_Release
        - Windows_arm64_Release
        - Linux_x64_Release
        - Linux_arm64_Release
        - Linux_Musl_x64_Release
        - Linux_Musl_arm64_Release
        - MacOS_x64_Release
        - MacOS_arm64_Release
        pool:
          name: NetCore1ESPool-Internal
          demands: ImageOverride -equals 1es-windows-2019
        enablePublishUsingPipelines: true
        enableMicrobuild: true
        artifacts:
          download:
            name: Build_Release
          publish:
            artifacts:
              name: Artifacts_Pack_Sign
            logs:
              name: Logs_Pack_Sign
            manifests: true
        variables:
        - _BuildConfig: Release
        - _SignType: real
        steps:
        - script: >-
            $(Build.SourcesDirectory)/eng/cipacksignpublish.cmd
            /p:TeamName=$(_TeamName)
            /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
            /p:DotNetSignType=real
            /p:DotNetPublishUsingPipelines=true
          displayName: Pack, Sign, and Publish
    # Register with BAR
    - template: /eng/common/templates/job/publish-build-assets.yml
      parameters:
        configuration: Release
        dependsOn:
        - Pack_Sign
        publishUsingPipelines: true
        pool:
          name: NetCore1ESPool-Internal
          demands: ImageOverride -equals 1es-windows-2019
# These are the stages that perform validation of several SDL requirements and publish the bits required to the designated feed.
- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - template: /eng/common/templates/post-build/post-build.yml
    parameters:
      # This is to enable SDL runs part of Post-Build Validation Stage.
      # as well as NuGet, SourceLink, and signing validation.
      # The variables get imported from group dotnet-diagnostics-sdl-params
      publishingInfraVersion: 3
      enableSourceLinkValidation: true
      enableSigningValidation: true
      enableSymbolValidation: false
      enableNugetValidation: true
      publishInstallersAndChecksums: true
      SDLValidationParameters:
        enable: true
        continueOnError: true
        params: ' -SourceToolsList @("policheck","credscan")
        -TsaInstanceURL $(_TsaInstanceURL)
        -TsaProjectName $(_TsaProjectName)
        -TsaNotificationEmail $(_TsaNotificationEmail)
        -TsaCodebaseAdmin $(_TsaCodebaseAdmin)
        -TsaBugAreaPath $(_TsaBugAreaPath)
        -TsaIterationPath $(_TsaIterationPath)
        -TsaRepositoryName "dotnet-monitor"
        -TsaCodebaseName "dotnet-monitor"
        -TsaPublish $True'
        artifactNames:
        - 'PackageArtifacts'
# This sets up the bits to do a Release.
- template: /eng/PrepareRelease.yml
