name: 'BuildKicker'
description: 'Retries check-runs until they succeeds'
inputs:
  requiredSuccesses:
    description: 'The number of check-runs from the same system that must succeed before attempting a retry on a specific check-run. For example, if we are going to try re-running a Azure DevOps CI on a check-suite with 10 Azure DevOps CIs, there must be 2 that succeed before we will retry failed ones.'
  pollInterval:
    description: 'The polling interval in minutes. Every [this value] minutes, the task will request the check-run status from github and do reruns.'
  commentId:
    description: 'The GitHub ID of the comment posted to the page that will be updated.'
  retries:
    description: 'Max number of retries to attempt for each check-run.'
  auth_token:
    description: 'The token used to authenticate to GitHub.'

runs:
  using: 'node12'
  main: 'buildkicker.js'
