name: 'Open PR'
description: 'Opens a PR targeting the currently checked out out branch.'
inputs:
  branch_name:
    description: 'The branch name to create. Will be prefixed with "bot/".'
    required: true
  title:
    description: 'The PR title.'
    required: true
  files_to_commit:
    description: 'The files to commit.'
    required: true
  commit_message:
    description: 'The commit message.'
    required: true
  body:
    description: 'The PR body.'
    required: true
  labels:
    description: 'Labels to add to the PR, comma separated.'
    required: false
  fail_if_files_unchanged:
    description: 'Fails the action if all of the specified files_to_commit are unchanged.'
    required: false
  auth_token:
    description: 'The token used to authenticate to GitHub.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Open PR
      run: |
        current_branch_name=$(git symbolic-ref --short HEAD)
        pr_branch_name=$(echo "bot/${{ inputs.branch_name }}" )

        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git checkout -b "$pr_branch_name"
        git add ${{ inputs.files_to_commit }}

        are_files_changed=""
        git diff --name-only --cached --exit-code || are_files_changed="1"
        if [ "$are_files_changed" != "1" ]; then
          echo "No files changed, nothing to do."
          if [ "${{ inputs.fail_if_files_unchanged }}" == "true" ]; then
            exit 1
          fi

          exit 0
        fi

        git commit -m "${{ inputs.commit_message }}"
        git push --force --set-upstream origin "HEAD:$pr_branch_name"

        gh pr create --repo "${{ github.repository }}" --base "$current_branch_name" -t "${{ inputs.title }}" -b  "${{ inputs.body }}" -l "${{ inputs.labels }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.auth_token }}
