trigger: none

pr:
  autoCancel: true
  branches:
    include:
    - main
    - release/*
    - internal/release/*
    - feature/*
  paths:
    exclude:
    - .devcontainer
    - .github
    - .vscode
    - .gitignore
    - cspell.json
    - eng/actions
    - '**.md'

parameters:
- name: testGroup
  displayName: 'Test Group'
  type: string
  default: Default
  values:
  - Default
  - All
  - None
  - CI
  - PR

variables:
- name: _TeamName
  value: DotNetCore

extends:
  template: /eng/pipelines/templates/pipeline-template.yml@self
  parameters:
    is1ESPipeline: false
    pool:
      name: NetCore-Svc-Public
      image: 1es-windows-2022-open
      os: windows
    stages:
    - stage: Build
      displayName: Build and Test
      jobs:
      # Build and (optionally) test binaries
      - template: /eng/pipelines/jobs/platform-matrix.yml@self
        parameters:
          jobTemplate: /eng/pipelines/jobs/build-test.yml@self
          includeDebug: true
          jobParameters:
            is1ESPipeline: false
            commonTemplatesFolderName: 'templates'

    # Build release staging tool
    - template: /eng/pipelines/stages/preparerelease.yml@self
      parameters:
        updateDockerCondition: false
        is1ESPipeline: false
