schedules:
- cron: "0 9 * * Mon-Fri"
  displayName: Shipped Component Governance Scan
  branches:
    include:
    - shipped/*
    exclude:
    - shipped/7.3
    - shipped/7.2
    - shipped/7.1
  always: true

trigger: none
pr: none

variables:
- name: _TeamName
  value: DotNetCore
# These branches represent shipped assets, thus use Svc build pool
- name: DncEngInternalBuildPool
  value: NetCore1ESPool-Svc-Internal

extends:
  template: /eng/pipelines/templates/pipeline-template.yml@self
  parameters:
    sdl:
      sbom:
        enabled: false
    stages:
    - stage: Build
      displayName: Build and Scan
      jobs:
      - template: /eng/pipelines/jobs/platform-matrix.yml@self
        parameters:
          jobTemplate: /eng/pipelines/jobs/build-binaries.yml@self
          includeArm64: true
          jobParameters:
            disableComponentGovernance: false
            disableSbom: true
            is1ESPipeline: true
