resources:
  pipelines:
  - pipeline: Build
    source: dotnet-dotnet-monitor

trigger: none
pr: none

variables:
- template: /eng/common/templates-official/variables/pool-providers.yml@self
- group: Release-Pipeline
- name: _TeamName
  value: DotNetCore
  readonly: true

extends:
  template: /eng/pipelines/templates/pipeline-template.yml@self
  parameters:
    sdl:
      sbom:
        enabled: false
    stages:
    - stage: Compliance

      jobs:
      - job: Validate
        timeoutInMinutes: 180

        workspace:
          clean: all

        steps:
        - task: PowerShell@2
          displayName: Get BAR ID
          inputs:
            filePath: $(Build.SourcesDirectory)/eng/release/Scripts/GetBarId.ps1
            arguments: >-
              -BuildId $(resources.pipeline.Build.runID)
              -TaskVariableName 'BuildBarId'
          env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)

        - task: PowerShell@2
          displayName: 'Get Build Version (Full)'
          inputs:
            filePath: $(Build.SourcesDirectory)/eng/release/Scripts/GetBuildVersion.ps1
            arguments: >-
              -BarId $(BuildBarId)
              -MaestroToken $(MaestroAccessToken)
              -TaskVariableName 'BuildVersion'

        - task: PowerShell@2
          displayName: 'Get Build Version (Major.Minor)'
          inputs:
            filePath: $(Build.SourcesDirectory)/eng/release/Scripts/GetBuildVersion.ps1
            arguments: >-
              -BarId $(BuildBarId)
              -MaestroToken $(MaestroAccessToken)
              -TaskVariableName 'BuildMajorMinorVersion'
              -MajorMinorOnly

        # Populate dotnetbuilds-internal-container-read-token
        - template: /eng/common/templates-official/steps/get-delegation-sas.yml
          parameters:
            federatedServiceConnection: 'dotnetbuilds-internal-read'
            outputVariableName: 'dotnetbuilds-internal-checksums-container-read-token'
            expiryInHours: 1
            base64Encode: false
            storageAccount: dotnetbuilds
            container: internal-checksums
            permissions: rl

        # Populate dotnetbuilds-internal-container-read-token
        - template: /eng/common/templates-official/steps/get-delegation-sas.yml
          parameters:
            federatedServiceConnection: 'dotnetbuilds-internal-read'
            outputVariableName: 'dotnetbuilds-internal-container-read-token'
            expiryInHours: 1
            base64Encode: false
            storageAccount: dotnetbuilds
            container: internal
            permissions: rl

        # Only scan the files that are being shipped; use the same gathering procedure
        # that the asset staging process uses.
        - task: PowerShell@2
          displayName: 'Download Build Assets'
          inputs:
            targetType: filePath
            filePath: '$(Build.Repository.LocalPath)/eng/release/Scripts/AcquireBuild.ps1'
            arguments: >-
              -BarBuildId "$(BuildBarId)"
              -AzdoToken "$(dn-bot-all-drop-rw-code-rw-release-all)"
              -DownloadTargetPath "$(System.ArtifactsDirectory)\BuildAssets"
              -SasSuffixes "$(dotnetbuilds-internal-checksums-container-read-token),$(dotnetbuilds-internal-container-read-token)"
              -ReleaseVersion "$(BuildVersion)"
              -Separated $False
            workingDirectory: '$(Build.Repository.LocalPath)'
          continueOnError: true

        # All of the relevant assets are packages, which must be extracted before scanning
        - task: PowerShell@2
          displayName: 'Extract Package Assets'
          inputs:
            targetType: filePath
            filePath: '$(Build.Repository.LocalPath)/eng/pipelines/scripts/Extract-Assets.ps1'
            arguments: >-
              -SourcePath '$(System.ArtifactsDirectory)\BuildAssets'
              -BinariesTargetPath '$(System.ArtifactsDirectory)\UnpackedBinaries'
              -SymbolsTargetPath '$(System.ArtifactsDirectory)\UnpackedSymbols'

        # Copy eligible files to be scanned
        - task: PowerShell@2
          displayName: 'Copy Eligible Assets'
          inputs:
            pwsh: true
            targetType: filePath
            filePath: '$(Build.Repository.LocalPath)/eng/pipelines/scripts/Copy-ApiScanEligible.ps1'
            arguments: >-
              -SourcePath '$(System.ArtifactsDirectory)\UnpackedBinaries'
              -TargetPath '$(System.ArtifactsDirectory)\ScannableBinaries'

        - task: AzureCLI@2
          displayName: 'Login to APISCan Identity (Step 1)'
          inputs:
            azureSubscription: 'dotnet-apiscan'
            scriptType: pscore
            scriptLocation: inlineScript
            addSpnToEnvironment: true
            inlineScript: |
                echo "##vso[task.setvariable variable=ARM_CLIENT_ID;issecret=true]$env:servicePrincipalId"
                echo "##vso[task.setvariable variable=ARM_ID_TOKEN;issecret=true]$env:idToken"
                echo "##vso[task.setvariable variable=ARM_TENANT_ID;issecret=true]$env:tenantId"
        # Re-log in
        - script: |
            az login --service-principal -u $(ARM_CLIENT_ID) --tenant $(ARM_TENANT_ID) --allow-no-subscriptions --federated-token $(ARM_ID_TOKEN)

          displayName: 'Login to APISCan Identity (Step 2)'

        - task: APIScan@2
          displayName: Run APIScan
          inputs:
            softwareFolder: '$(System.ArtifactsDirectory)\ScannableBinaries'
            softwareName: 'DotnetMonitor'
            softwareVersionNum: '$(BuildMajorMinorVersion)'
            softwareBuildNum: '$(resources.pipeline.Build.runID)'
            symbolsFolder: 'SRV*http://symweb;$(System.ArtifactsDirectory)\UnpackedSymbols'
          env:
            AzureServicesAuthConnectionString: RunAs=Developer;DeveloperTool=AzureCli
          continueOnError: true

        - task: PublishSecurityAnalysisLogs@3
          displayName: Publish Analysis
          inputs:
            ArtifactName: 'CodeAnalysisLogs'
            ArtifactType: 'Container'
            AllTools: false
            ApiScan: true
            ToolLogsNotFoundAction: 'Standard'

        - task: PostAnalysis@2
          displayName: Fail if Issues are Detected
          condition: succeededOrFailed()
          inputs:
            GdnBreakAllTools: true
            GdnBreakGdnToolApiScanSeverity: Warning
