<Project>
  <!--
    Packages in this file have versions updated periodically by Dependabot specifically from nuget.org.
  -->
  <ItemGroup>
    <!-- dotnet/diagnostics references -->
    <!--
      Keep MicrosoftDiagnosticsMonitoringShippedVersion in-sync with the latest version of Microsoft.Diagnostics.DbgShim
      on the dotnet-tools feed:
      - Microsoft.Diagnostics.Monitoring.* packages are available from the dotnet-tools feed.
      - Microsoft.Diagnostics.DbgShim, and select other packages from dotnet/diagnostics, share the same version tag as the
        Microsoft.Diagnostics.Monitoring.* packages, so tracking DbgShim from the same feed keeps their versions aligned.
      - This project is evaluated by dependabot using msbuild, so we have to use a package that can actually be restored,
        so use Microsoft.Diagnostics.DbgShim.
    -->
    <PackageReference Include="Microsoft.Diagnostics.DbgShim" Version="$(MicrosoftDiagnosticsMonitoringShippedVersion)" />
  </ItemGroup>
</Project>
