<Project>
  <!-- Import references updated by Dependabot. -->
  <PropertyGroup>
    <!-- Microsoft.AspNetCore.Authentication.Negotiate -->
    <MicrosoftAspNetCoreAuthenticationNegotiate90Version>9.0.18</MicrosoftAspNetCoreAuthenticationNegotiate90Version>
    <!-- Microsoft.Extensions.Configuration.Abstractions -->
    <MicrosoftExtensionsConfigurationAbstractions90Version>9.0.18</MicrosoftExtensionsConfigurationAbstractions90Version>
    <!-- Microsoft.Extensions.Logging -->
    <MicrosoftExtensionsLogging90Version>9.0.18</MicrosoftExtensionsLogging90Version>
    <!-- Microsoft.Extensions.Logging.Abstractions -->
    <MicrosoftExtensionsLoggingAbstractions90Version>9.0.18</MicrosoftExtensionsLoggingAbstractions90Version>
    <!-- Microsoft.Extensions.Logging.Console -->
    <MicrosoftExtensionsLoggingConsole90Version>9.0.18</MicrosoftExtensionsLoggingConsole90Version>
    <!-- Microsoft.NETCore.App -->
    <MicrosoftNETCoreApp90Version>9.0.14</MicrosoftNETCoreApp90Version>
    <!-- System.Security.Cryptography.Xml -->
    <SystemSecurityCryptographyXml90Version>9.0.18</SystemSecurityCryptographyXml90Version>
    <!-- System.Text.Json -->
    <SystemTextJson90Version>9.0.18</SystemTextJson90Version>
  </PropertyGroup>
</Project>
