# Builds and tests dotnet-monitor for a specific platform and configuration

parameters:
  # Operating system group (Windows, Linux, MacOS, etc)
  osGroup: Windows
  # Build configuration (Debug, Release)
  configuration: Release
  # Build architecture (arm64, x64, x86, etc)
  architecture: x64

jobs:
- template: /eng/pipelines/jobs/build.yml@self
  parameters:
    prefix: Archive
    osGroup: ${{ parameters.osGroup }}
    configuration: ${{ parameters.configuration }}
    architecture: ${{ parameters.architecture }}
    dependsOn:
    - Sign_Binaries

    preBuildSteps:
    - task: DownloadPipelineArtifact@2
      displayName: Download Signed Artifacts
      inputs:
        artifactName: Build_Signed_${{ parameters.configuration }}
        targetPath: '$(Build.SourcesDirectory)/artifacts'
    - task: DownloadPipelineArtifact@2
      displayName: Download Third Party Notice
      inputs:
        artifactName: 'THIRD-PARTY-NOTICES'
        targetPath: '$(Build.SourcesDirectory)'

    buildArgs: >-
      -archive
      -pack
      -skipmanaged
      -skipnative
      /p:PublishProjectsAfterBuild=true
      /p:ThirdPartyNoticesFilePath='$(Build.SourcesDirectory)/$(_TPNFile)'

    postBuildSteps:
    - task: CopyFiles@2
      displayName: Gather Artifacts (packages)
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/artifacts/packages'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/artifacts/packages'

    - task: 1ES.PublishBuildArtifacts@1
      displayName: Publish Artifacts (Unified)
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/artifacts'
        ArtifactName: Archive_Unified_${{ parameters.configuration }}
