jobs:
- template: /eng/common/templates-official/job/job.yml@self
  parameters:
    name: Pack_Sign
    displayName: Pack and Sign
    enablePublishUsingPipelines: true
    enableMicrobuild: true
    artifacts:
      publish:
        artifacts:
          name: Artifacts_Pack_Sign
        # logs:
        #   name: Logs_Pack_Sign # Log publishing isn't ported over in arcade yet
        manifests: true
    variables:
    - _BuildConfig: Release
    - _SignType: real
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download Binaries
      inputs:
        artifactName: Build_Unified_Release
        targetPath: '$(Build.SourcesDirectory)/artifacts'
    - task: DownloadPipelineArtifact@2
      displayName: Download Archives
      inputs:
        artifactName: Archive_Unified_Release
        targetPath: '$(Build.SourcesDirectory)/artifacts'
    - task: DownloadPipelineArtifact@2
      displayName: Download Third Party Notice
      inputs:
        artifactName: 'THIRD-PARTY-NOTICES'
        targetPath: '$(Build.SourcesDirectory)'
    - script: >-
        $(Build.SourcesDirectory)/eng/cipacksignpublish.cmd
        /p:TeamName=$(_TeamName)
        /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
        /p:DotNetSignType=real
        /p:DotNetPublishUsingPipelines=true
        /p:ThirdPartyNoticesFilePath='$(Build.SourcesDirectory)/$(_TPNFile)'
      displayName: Pack, Sign, and Publish
    # Intentionally copying file as "dotnet-monitor.nupkg.buildversion" for back compat
    - task: powershell@2
      displayName: Generate Build Info
      inputs:
        targetType: inline
        script: |
          New-Item "$(Build.ArtifactStagingDirectory)/buildInfo" -Type Directory
          Copy-Item "$(Build.SourcesDirectory)/artifacts/packages/Release/Shipping/dotnet-monitor.buildversion" "$(Build.ArtifactStagingDirectory)/buildInfo/dotnet-monitor.nupkg.buildversion"
    - task: 1ES.PublishPipelineArtifact@1
      displayName: Publish Build Info
      inputs:
        artifactName: 'Build_Info'
        targetPath: $(Build.ArtifactStagingDirectory)/buildInfo
