jobs:
- template: /eng/common/templates/job/job.yml
  parameters:
    name: Pack_Sign
    displayName: Pack and Sign
    pool:
      name: NetCore1ESPool-Svc-Internal
      demands: ImageOverride -equals 1es-windows-2019
    enablePublishUsingPipelines: true
    enableMicrobuild: true
    artifacts:
      publish:
        artifacts:
          name: Artifacts_Pack_Sign
        logs:
          name: Logs_Pack_Sign
        manifests: true
    variables:
    - _BuildConfig: Release
    - _SignType: real
    - group: DotNetBuilds storage account read tokens
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download Binaries
      inputs:
        artifactName: Build_Unified_Release
        targetPath: '$(Build.SourcesDirectory)/artifacts'
    - task: DownloadPipelineArtifact@2
      displayName: Download Archives
      inputs:
        artifactName: Archive_Unified_Release
        targetPath: '$(Build.SourcesDirectory)/artifacts'
    - task: DownloadPipelineArtifact@2
      displayName: Download Third Party Notice
      inputs:
        artifactName: 'THIRD-PARTY-NOTICES'
        targetPath: '$(Build.SourcesDirectory)'
    - template: /eng/pipelines/steps/setup-nuget-sources.yml
      parameters:
        osGroup: Windows
    - script: >-
        $(Build.SourcesDirectory)/eng/cipacksignpublish.cmd
        /p:TeamName=$(_TeamName)
        /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
        /p:DotNetSignType=real
        /p:DotNetPublishUsingPipelines=true
        /p:SkipPublishProjects=true
        /p:ThirdPartyNoticesFilePath='$(Build.SourcesDirectory)/$(_TPNFile)'
        /p:DotNetRuntimeSourceFeed=https://dotnetbuilds.blob.core.windows.net/internal
        /p:DotNetRuntimeSourceFeedKey=$(dotnetbuilds-internal-container-read-token-base64)
      displayName: Pack, Sign, and Publish
    # Intentionally copying file as "dotnet-monitor.nupkg.buildversion" for back compat
    - task: powershell@2
      displayName: Generate Build Info
      inputs:
        targetType: inline
        script: |
            New-Item "$(Build.ArtifactStagingDirectory)/buildInfo" -Type Directory
            Copy-Item "$(Build.SourcesDirectory)/artifacts/packages/Release/Shipping/dotnet-monitor-*-win-x64.zip.buildversion" "$(Build.ArtifactStagingDirectory)/buildInfo/dotnet-monitor.nupkg.buildversion"
    - task: PublishPipelineArtifact@1
      displayName: Publish Build Info
      inputs:
        artifactName: 'Build_Info'
        targetPath: $(Build.ArtifactStagingDirectory)/buildInfo
