parameters:
  # Build configuration (Debug, Release)
  configuration: Release

jobs:
- template: /eng/common/templates-official/job/job.yml@self
  parameters:
    name: Sign_Binaries
    displayName: Sign Binaries
    enableMicrobuild: true
    artifacts:
      publish:
        logs:
          name: Logs_Sign_Binaries
    variables:
    - _BuildConfig: ${{ parameters.configuration }}
    - _SignType: real
    - group: DotNet-MSRC-Storage
    - _InternalBuildArgs: ''
    - _InternalInstallArgs: >-
        -RuntimeSourceFeed https://dotnetclimsrc.blob.core.windows.net/dotnet
        -RuntimeSourceFeedKey $(dotnetclimsrc-read-sas-token-base64)

    - ${{ if notin(variables['Build.Reason'], 'PullRequest') }}:
      - _InternalBuildArgs: >-
          /p:TeamName=$(_TeamName)
          /p:OfficialBuildId=$(BUILD.BUILDNUMBER)

    steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download Build
      inputs:
        artifactName: Build_Published_${{ parameters.configuration }}
        targetPath: '$(Build.SourcesDirectory)/artifacts'

    - task: PowerShell@2
      displayName: Setup Private Feeds Credentials
      inputs:
        filePath: $(Build.SourcesDirectory)/eng/common/SetupNugetSources.ps1
        arguments: -ConfigFile $(Build.SourcesDirectory)/NuGet.config -Password $Env:Token
      env:
        Token: $(dn-bot-dnceng-artifact-feeds-rw)

    - script: >-
        $(Build.SourcesDirectory)/restore.cmd
        -configuration ${{ parameters.configuration }}
        -verbosity minimal
        -ci
        -preparemachine
        -sign
        -nobl
        /bl:'$(Build.SourcesDirectory)\artifacts\log\Release\SignBinaries.binlog'
        /p:DotNetSignType=real
        /p:SignAllBinaries=true
        $(_InternalInstallArgs)
        $(_InternalBuildArgs)
      displayName: Sign

    - task: CopyFiles@2
      displayName: Gather Artifacts (bin)
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/artifacts/bin'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/artifacts/bin'

    - task: CopyFiles@2
      displayName: Gather Artifacts (pub)
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/artifacts/pub'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/artifacts/pub'

    - task: 1ES.PublishBuildArtifacts@1
      displayName: Publish Artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/artifacts'
        ArtifactName: Build_Signed_${{ parameters.configuration }}
