parameters:
  # Build configuration (Debug, Release)
  configuration: Release

jobs:
- template: /eng/common/templates-official/job/job.yml@self
  parameters:
    name: Sign_Binaries
    displayName: Sign Binaries
    enableMicrobuild: true
    artifacts:
      publish:
        logs:
          name: Logs_Sign_Binaries
    variables:
    - _BuildConfig: ${{ parameters.configuration }}
    - _SignType: real

    steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download Build
      inputs:
        artifactName: Build_Published_${{ parameters.configuration }}
        targetPath: '$(Build.SourcesDirectory)/artifacts'

    - template: /eng/pipelines/steps/setup-nuget-sources.yml@self
      parameters:
        osGroup: Windows

    # Populate internal runtime access variables
    - template: /eng/common/templates/steps/enable-internal-runtimes.yml

    - script: >-
        $(Build.SourcesDirectory)/restore.cmd
        -configuration ${{ parameters.configuration }}
        -verbosity minimal
        -ci
        -preparemachine
        -sign
        -nobl
        /bl:'$(Build.SourcesDirectory)\artifacts\log\Release\SignBinaries.binlog'
        /p:TeamName=$(_TeamName)
        /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
        /p:DotNetSignType=real
        /p:SignAllBinaries=true
        /p:DotNetRuntimeSourceFeed=https://dotnetbuilds.blob.core.windows.net/internal
        /p:DotNetRuntimeSourceFeedKey=$(dotnetbuilds-internal-container-read-token-base64)
      displayName: Sign

    - task: CopyFiles@2
      displayName: Gather Artifacts (bin)
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/artifacts/bin'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/artifacts/bin'

    - task: CopyFiles@2
      displayName: Gather Artifacts (pub)
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/artifacts/pub'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/artifacts/pub'

    - task: 1ES.PublishBuildArtifacts@1
      displayName: Publish Artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/artifacts'
        ArtifactName: Build_Signed_${{ parameters.configuration }}
