jobs:
- template: /eng/common/templates/job/job.yml
  parameters:
    name: Generate_TPN
    displayName: Generate TPN
    disableComponentGovernance: true
    enableSbom: false
    pool:
      name: NetCore1ESPool-Svc-Internal
      demands: ImageOverride -equals 1es-windows-2019
    steps:
    # Only restore the dotnet-monitor project so only packages we ship get included in the below CG scan
    - script: >-
        $(Build.SourcesDirectory)/restore.cmd -ci -projects $(Build.SourcesDirectory)/src/Tools/dotnet-monitor/dotnet-monitor.csproj
      displayName: Restore dotnet-monitor tool packages
        
    - task: ComponentGovernanceComponentDetection@0
      displayName: Component Detection (dotnet-monitor tool)

    - task: notice@0
      displayName: Generate TPN file
      inputs:
        outputfile: '$(Build.ArtifactStagingDirectory)/$(_TPNFile)'
        outputformat: text

    - task: PublishPipelineArtifact@1
      displayName: Publish TPN
      inputs:
        artifactName: 'THIRD-PARTY-NOTICES'
        targetPath: '$(Build.ArtifactStagingDirectory)/$(_TPNFile)'
