jobs:
- template: /eng/common/templates-official/job/job.yml@self
  parameters:
    name: Generate_TPN
    displayName: Generate TPN
    disableComponentGovernance: true
    enableSbom: false
    variables:
    - _InternalInstallArgs: ''
    - ${{ if eq(variables['System.TeamProject'], 'internal') }}:
      - _InternalInstallArgs: >-
          /p:DotNetRuntimeSourceFeed=https://dotnetbuilds.blob.core.windows.net/internal
          /p:DotNetRuntimeSourceFeedKey=$(dotnetbuilds-internal-container-read-token-base64)
    steps:
    - template: /eng/pipelines/steps/setup-nuget-sources.yml@self
      parameters:
        osGroup: Windows

    # Populate internal runtime access variables
    - template: /eng/common/templates/steps/enable-internal-runtimes.yml

    # Only restore the projects that are shipped so only packages we ship get included in the below CG scan
    - script: >-
        $(Build.SourcesDirectory)/restore.cmd -ci
        -projects $(Build.SourcesDirectory)/src/Extensions/AzureBlobStorage/AzureBlobStorage.csproj
        $(_InternalInstallArgs)
      displayName: Restore AzureBlobStorage

    - script: >-
        $(Build.SourcesDirectory)/restore.cmd -ci
        -projects $(Build.SourcesDirectory)/src/Tools/dotnet-monitor/dotnet-monitor.csproj
        $(_InternalInstallArgs)
      displayName: Restore dotnet-monitor

    - script: >-
        $(Build.SourcesDirectory)/restore.cmd -ci
        -projects $(Build.SourcesDirectory)/src/Extensions/S3Storage/S3Storage.csproj
        $(_InternalInstallArgs)
      displayName: Restore S3Storage

    - task: ComponentGovernanceComponentDetection@0
      displayName: Component Detection

    - task: notice@0
      displayName: Generate TPN file
      retryCountOnTaskFailure: 5
      inputs:
        outputfile: '$(Build.ArtifactStagingDirectory)/$(_TPNFile)'
        outputformat: text

    - task: 1ES.PublishPipelineArtifact@1
      displayName: Publish TPN
      inputs:
        artifactName: 'THIRD-PARTY-NOTICES'
        targetPath: '$(Build.ArtifactStagingDirectory)/$(_TPNFile)'
