jobs:
- template: /eng/common/templates/job/job.yml
  parameters:
    name: Generate_TPN
    displayName: Generate TPN
    disableComponentGovernance: true
    enableSbom: false
    pool:
      name: $(DncEngInternalBuildPool)
      demands: ImageOverride -equals 1es-windows-2019
    variables:
    - _InternalInstallArgs: ''
    - ${{ if eq(variables['System.TeamProject'], 'internal') }}:
      - group: DotNetBuilds storage account read tokens
      - _InternalInstallArgs: >-
          /p:DotNetRuntimeSourceFeed=https://dotnetbuilds.blob.core.windows.net/internal
          /p:DotNetRuntimeSourceFeedKey=$(dotnetbuilds-internal-container-read-token-base64)
    steps:
    - task: PowerShell@2
      displayName: Setup Private Feeds Credentials
      inputs:
        filePath: $(Build.SourcesDirectory)/eng/common/SetupNugetSources.ps1
        arguments: -ConfigFile $(Build.SourcesDirectory)/NuGet.config -Password $Env:Token
      env:
        Token: $(dn-bot-dnceng-artifact-feeds-rw)
    # Only restore the projects that are shipped so only packages we ship get included in the below CG scan
    - script: >-
        $(Build.SourcesDirectory)/restore.cmd -ci
        -projects $(Build.SourcesDirectory)/src/Extensions/AzureBlobStorage/AzureBlobStorage.csproj
        $(_InternalInstallArgs)
      displayName: Restore AzureBlobStorage

    - script: >-
        $(Build.SourcesDirectory)/restore.cmd -ci
        -projects $(Build.SourcesDirectory)/src/Tools/dotnet-monitor/dotnet-monitor.csproj
        $(_InternalInstallArgs)
      displayName: Restore dotnet-monitor
    
    - script: >-
        $(Build.SourcesDirectory)/restore.cmd -ci
        -projects $(Build.SourcesDirectory)/src/Extensions/S3Storage/S3Storage.csproj
        $(_InternalInstallArgs)
      displayName: Restore S3Storage
        
    - task: ComponentGovernanceComponentDetection@0
      displayName: Component Detection

    - task: notice@0
      displayName: Generate TPN file
      inputs:
        outputfile: '$(Build.ArtifactStagingDirectory)/$(_TPNFile)'
        outputformat: text

    - task: PublishPipelineArtifact@1
      displayName: Publish TPN
      inputs:
        artifactName: 'THIRD-PARTY-NOTICES'
        targetPath: '$(Build.ArtifactStagingDirectory)/$(_TPNFile)'
