jobs:
- template: /eng/common/templates-official/job/job.yml@self
  parameters:
    name: Generate_TPN
    displayName: Generate TPN
    disableComponentGovernance: true
    enableSbom: false
    steps:
    # Only restore the dotnet-monitor project so only packages we ship get included in the below CG scan
    - script: >-
        $(Build.SourcesDirectory)/restore.cmd -ci -projects $(Build.SourcesDirectory)/src/Tools/dotnet-monitor/dotnet-monitor.csproj
      displayName: Restore dotnet-monitor tool packages
        
    - task: ComponentGovernanceComponentDetection@0
      displayName: Component Detection (dotnet-monitor tool)

    - task: notice@0
      displayName: Generate TPN file
      inputs:
        outputfile: '$(Build.ArtifactStagingDirectory)/$(_TPNFile)'
        outputformat: text

    - task: 1ES.PublishPipelineArtifact@1
      displayName: Publish TPN
      inputs:
        artifactName: 'THIRD-PARTY-NOTICES'
        targetPath: '$(Build.ArtifactStagingDirectory)/$(_TPNFile)'
