jobs:
- template: /eng/common/templates/job/job.yml
  parameters:
    name: Generate_TPN
    displayName: Generate TPN
    disableComponentGovernance: true
    enableSbom: false
    pool:
      name: $(DncEngInternalBuildPool)
      demands: ImageOverride -equals 1es-windows-2019
    steps:
    # Only restore the projects that are shipped so only packages we ship get included in the below CG scan
    - script: >-
        $(Build.SourcesDirectory)/restore.cmd -ci -projects $(Build.SourcesDirectory)/src/Extensions/AzureBlobStorage/AzureBlobStorage.csproj
      displayName: Restore AzureBlobStorage

    - script: >-
        $(Build.SourcesDirectory)/restore.cmd -ci -projects $(Build.SourcesDirectory)/src/Tools/dotnet-monitor/dotnet-monitor.csproj
      displayName: Restore dotnet-monitor
    
    - script: >-
        $(Build.SourcesDirectory)/restore.cmd -ci -projects $(Build.SourcesDirectory)/src/Extensions/S3Storage/S3Storage.csproj
      displayName: Restore S3Storage
        
    - task: ComponentGovernanceComponentDetection@0
      displayName: Component Detection

    - task: notice@0
      displayName: Generate TPN file
      inputs:
        outputfile: '$(Build.ArtifactStagingDirectory)/$(_TPNFile)'
        outputformat: text

    - task: PublishPipelineArtifact@1
      displayName: Publish TPN
      inputs:
        artifactName: 'THIRD-PARTY-NOTICES'
        targetPath: '$(Build.ArtifactStagingDirectory)/$(_TPNFile)'
