// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

// Trim-analysis suppressions for the self-contained, fully-trimmed tool build
// (dotnet-monitor-selfcontained; see SelfContainedTool.targets).
//
// Every type listed here performs reflection that the trimmer flags under TrimMode=full
// (reflection-based JSON serialization, reflection-based configuration binding, minimal-API
// endpoint mapping, or DataAnnotations validation - including [Range(typeof(TimeSpan), ...)]
// and [MinLength] on the collection-rule options). The reflected/serialized/validated type
// sets all live in assemblies that are preserved whole by the TrimmerRootAssembly items in
// SelfContainedTool.targets (dotnet-monitor, Microsoft.Diagnostics.Monitoring.WebApi,
// Microsoft.Diagnostics.Monitoring.Options and System.ComponentModel.TypeConverter), so the
// members the reflection touches are not actually removed and the flagged code is safe.
//
// These attributes are inert in the framework-dependent build and the container image (no
// trimming happens there); they only take effect when the self-contained tool is published.

using System.Diagnostics.CodeAnalysis;

[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.Auth.ApiKey.GeneratedJwtKey", Justification = "Reflection target type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.Auth.ApiKey.MonitorApiKeyPostConfigure", Justification = "Reflection target type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.Auth.AuthConfiguratorFactory", Justification = "Reflection target type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.Auth.AzureAd.AzureAdAuthConfigurator", Justification = "Reflection target type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions.CollectDumpActionFactory", Justification = "Reflection target type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions.CollectExceptionsActionFactory", Justification = "Reflection target type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions.CollectGCDumpActionFactory", Justification = "Reflection target type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions.CollectLiveMetricsActionFactory", Justification = "Reflection target type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions.CollectLogsActionFactory", Justification = "Reflection target type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions.CollectStacksActionFactory", Justification = "Reflection target type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions.CollectTraceActionFactory", Justification = "Reflection target type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions.ExecuteActionFactory", Justification = "Reflection target type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions.GetEnvironmentVariableActionFactory", Justification = "Reflection target type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions.LoadProfilerActionFactory", Justification = "Reflection target type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions.SetEnvironmentVariableActionFactory", Justification = "Reflection target type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options.Actions.CollectLiveMetricsOptions", Justification = "[Range(typeof(TimeSpan))]/[MinLength] validation over a type set preserved via TrimmerRootAssembly (incl. System.ComponentModel.TypeConverter) in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options.Actions.CollectLogsOptions", Justification = "[Range(typeof(TimeSpan))]/[MinLength] validation over a type set preserved via TrimmerRootAssembly (incl. System.ComponentModel.TypeConverter) in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options.Actions.CollectTraceOptions", Justification = "[Range(typeof(TimeSpan))]/[MinLength] validation over a type set preserved via TrimmerRootAssembly (incl. System.ComponentModel.TypeConverter) in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options.CollectionRuleLimitsDefaultsOptions", Justification = "[Range(typeof(TimeSpan))]/[MinLength] validation over a type set preserved via TrimmerRootAssembly (incl. System.ComponentModel.TypeConverter) in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options.CollectionRuleLimitsOptions", Justification = "[Range(typeof(TimeSpan))]/[MinLength] validation over a type set preserved via TrimmerRootAssembly (incl. System.ComponentModel.TypeConverter) in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options.CollectionRuleOptions", Justification = "DataAnnotations validation over a type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options.CollectionRuleTriggerDefaultsOptions", Justification = "[Range(typeof(TimeSpan))]/[MinLength] validation over a type set preserved via TrimmerRootAssembly (incl. System.ComponentModel.TypeConverter) in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options.ValidationHelper", Justification = "DataAnnotations validation over a type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options.Triggers.AspNetRequestCountOptions", Justification = "[Range(typeof(TimeSpan))]/[MinLength] validation over a type set preserved via TrimmerRootAssembly (incl. System.ComponentModel.TypeConverter) in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options.Triggers.AspNetRequestDurationOptions", Justification = "[Range(typeof(TimeSpan))]/[MinLength] validation over a type set preserved via TrimmerRootAssembly (incl. System.ComponentModel.TypeConverter) in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options.Triggers.AspNetResponseStatusOptions", Justification = "[Range(typeof(TimeSpan))]/[MinLength] validation over a type set preserved via TrimmerRootAssembly (incl. System.ComponentModel.TypeConverter) in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options.Triggers.EventCounterOptions", Justification = "[Range(typeof(TimeSpan))]/[MinLength] validation over a type set preserved via TrimmerRootAssembly (incl. System.ComponentModel.TypeConverter) in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options.Triggers.EventMeterOptions", Justification = "[Range(typeof(TimeSpan))]/[MinLength] validation over a type set preserved via TrimmerRootAssembly (incl. System.ComponentModel.TypeConverter) in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options.Triggers.EventCounterShortcuts.CPUUsageOptions", Justification = "[Range(typeof(TimeSpan))]/[MinLength] validation over a type set preserved via TrimmerRootAssembly (incl. System.ComponentModel.TypeConverter) in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options.Triggers.EventCounterShortcuts.GCHeapSizeOptions", Justification = "[Range(typeof(TimeSpan))]/[MinLength] validation over a type set preserved via TrimmerRootAssembly (incl. System.ComponentModel.TypeConverter) in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options.Triggers.EventCounterShortcuts.ThreadpoolQueueLengthOptions", Justification = "[Range(typeof(TimeSpan))]/[MinLength] validation over a type set preserved via TrimmerRootAssembly (incl. System.ComponentModel.TypeConverter) in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.Commands.GenerateApiKeyCommandHandler", Justification = "Reflection-based JSON serialization over a type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.Egress.EgressExtension", Justification = "Reflection-based JSON serialization over a type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.Egress.EgressExtension.OutputParser`1", Justification = "Reflection-based JSON deserialization over a type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.Exceptions.ExceptionsOperation", Justification = "Reflection-based JSON serialization over a type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.Extensibility.ExtensionManifest", Justification = "Reflection-based JSON (de)serialization over a type set preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.TestAssemblies", Justification = "DEBUG-only assembly-load helper preserved whole via TrimmerRootAssembly; not used on the self-contained release path.")]

// IL2075 - reflection over the runtime type of a configuration/options object (obj.GetType().GetProperties()/
// GetMethod()). The objects are dotnet-monitor option/settings types preserved whole via TrimmerRootAssembly, so
// their members survive trimming. TestAssemblies is a DEBUG-only helper preserved by rooting.
[assembly: UnconditionalSuppressMessage("Trimming", "IL2075", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.CommonOptionsExtensions", Justification = "Reflected option object types preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2075", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.ConfigurationTokenParser", Justification = "Reflected settings object types preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2075", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.TestAssemblies", Justification = "DEBUG-only assembly-load helper preserved whole via TrimmerRootAssembly; not used on the self-contained release path.")]

// IL2026 - the generic DataAnnotations validation funnel. The validated option types (the concrete TOptions
// arguments) are preserved whole via TrimmerRootAssembly, so reflective validation is safe.
[assembly: UnconditionalSuppressMessage("Trimming", "IL2026", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.DataAnnotationValidateOptions`1", Justification = "Validated option types preserved via TrimmerRootAssembly in the self-contained build.")]

// IL2091 - generic type parameters flowed into DI registration / the options cache that require
// DynamicallyAccessedMembers. Every concrete type argument used at the call sites lives in an assembly preserved
// whole via TrimmerRootAssembly, so the required members (public/parameterless constructors) are not trimmed.
[assembly: UnconditionalSuppressMessage("Trimming", "IL2091", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.DynamicNamedOptionsCache`1", Justification = "Concrete TOptions arguments preserved via TrimmerRootAssembly in the self-contained build.")]
[assembly: UnconditionalSuppressMessage("Trimming", "IL2091", Scope = "type", Target = "T:Microsoft.Diagnostics.Tools.Monitor.ServiceCollectionExtensions", Justification = "Concrete factory/descriptor/options arguments preserved via TrimmerRootAssembly in the self-contained build.")]

