// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using __OptionValidationStaticInstances;
using Microsoft.Diagnostics.Monitoring.Options;
using Microsoft.Diagnostics.Monitoring.WebApi;
using Microsoft.Diagnostics.Monitoring.WebApi.Models;
using Microsoft.Diagnostics.Monitoring.WebApi.Validation;
using Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options;
using Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options.Actions;
using Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options.Triggers;
using Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options.Triggers.EventCounterShortcuts;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.Tracing;
using System.Globalization;

// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // Compensate for https://github.com/dotnet/roslyn/issues/54103
namespace Microsoft.Diagnostics.Monitoring.WebApi.Models
{
    internal sealed partial class __EventMetricsMeterValidator__
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public static ValidateOptionsResult Validate(string? name, EventMetricsMeter options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "EventMetricsMeter.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, null, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(2);

            context.MemberName = "MeterName";
            context.DisplayName = "EventMetricsMeter.MeterName";
            validationAttributes.Add(__Attributes.A1);
            validationAttributes.Add(__Attributes.A2);
            if (!Validator.TryValidateValue(options.MeterName, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Monitoring.WebApi.Models
{
    internal sealed partial class __EventMetricsProviderValidator__
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public static ValidateOptionsResult Validate(string? name, EventMetricsProvider options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "EventMetricsProvider.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, null, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(2);

            context.MemberName = "ProviderName";
            context.DisplayName = "EventMetricsProvider.ProviderName";
            validationAttributes.Add(__Attributes.A1);
            validationAttributes.Add(__Attributes.A2);
            if (!Validator.TryValidateValue(options.ProviderName, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Monitoring.WebApi.Models
{
    internal sealed partial class __EventPipeProviderValidator__
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public static ValidateOptionsResult Validate(string? name, EventPipeProvider options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "EventPipeProvider.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, null, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(2);

            context.MemberName = "Name";
            context.DisplayName = "EventPipeProvider.Name";
            validationAttributes.Add(__Attributes.A1);
            validationAttributes.Add(__Attributes.A2);
            if (!Validator.TryValidateValue(options.Name, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "Keywords";
            context.DisplayName = "EventPipeProvider.Keywords";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A3);
            if (!Validator.TryValidateValue(options.Keywords, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "EventLevel";
            context.DisplayName = "EventPipeProvider.EventLevel";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A4);
            if (!Validator.TryValidateValue(options.EventLevel, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions
{
    partial class CollectDumpActionDescriptor
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public ValidateOptionsResult Validate(string? name, CollectDumpOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "CollectDumpOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, _serviceProvider, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(2);

            context.MemberName = "Type";
            context.DisplayName = "CollectDumpOptions.Type";
            validationAttributes.Add(__Attributes.A5);
            if (!Validator.TryValidateValue(options.Type, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "Egress";
            context.DisplayName = "CollectDumpOptions.Egress";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A6);
            validationAttributes.Add(__Attributes.A7);
            if (!Validator.TryValidateValue(options.Egress, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions
{
    partial class CollectExceptionsActionDescriptor
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public ValidateOptionsResult Validate(string? name, CollectExceptionsOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "CollectExceptionsOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, _serviceProvider, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(2);

            context.MemberName = "Egress";
            context.DisplayName = "CollectExceptionsOptions.Egress";
            validationAttributes.Add(__Attributes.A6);
            validationAttributes.Add(__Attributes.A7);
            if (!Validator.TryValidateValue(options.Egress, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "Validate";
            context.DisplayName = "CollectExceptionsOptions.Validate";
            (builder ??= new()).AddResults(((IValidatableObject)options).Validate(context));

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions
{
    partial class CollectGCDumpActionDescriptor
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public ValidateOptionsResult Validate(string? name, CollectGCDumpOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "CollectGCDumpOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, _serviceProvider, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(2);

            context.MemberName = "Egress";
            context.DisplayName = "CollectGCDumpOptions.Egress";
            validationAttributes.Add(__Attributes.A6);
            validationAttributes.Add(__Attributes.A7);
            if (!Validator.TryValidateValue(options.Egress, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions
{
    partial class CollectLiveMetricsActionDescriptor
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public ValidateOptionsResult Validate(string? name, CollectLiveMetricsOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "CollectLiveMetricsOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, _serviceProvider, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(2);

            if (options.Providers is not null)
            {
                var count = 0;
                foreach (var o in options.Providers)
                {
                    if (o is not null)
                    {
                        (builder ??= new()).AddResult(__EventMetricsProviderValidator__.Validate(string.IsNullOrEmpty(name) ? $"CollectLiveMetricsOptions.Providers[{count}]" : $"{name}.Providers[{count}]", o));
                    }
                    else
                    {
                        (builder ??= new()).AddError(string.IsNullOrEmpty(name) ? $"CollectLiveMetricsOptions.Providers[{count}] is null" : $"{name}.Providers[{count}] is null");
                    }
                    count++;
                }
            }

            if (options.Meters is not null)
            {
                var count = 0;
                foreach (var o in options.Meters)
                {
                    if (o is not null)
                    {
                        (builder ??= new()).AddResult(__EventMetricsMeterValidator__.Validate(string.IsNullOrEmpty(name) ? $"CollectLiveMetricsOptions.Meters[{count}]" : $"{name}.Meters[{count}]", o));
                    }
                    else
                    {
                        (builder ??= new()).AddError(string.IsNullOrEmpty(name) ? $"CollectLiveMetricsOptions.Meters[{count}] is null" : $"{name}.Meters[{count}] is null");
                    }
                    count++;
                }
            }

            context.MemberName = "Duration";
            context.DisplayName = "CollectLiveMetricsOptions.Duration";
            validationAttributes.Add(__Attributes.A8);
            if (!Validator.TryValidateValue(options.Duration, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "Egress";
            context.DisplayName = "CollectLiveMetricsOptions.Egress";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A6);
            validationAttributes.Add(__Attributes.A7);
            if (!Validator.TryValidateValue(options.Egress, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions
{
    partial class CollectLogsActionDescriptor
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public ValidateOptionsResult Validate(string? name, CollectLogsOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "CollectLogsOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, _serviceProvider, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(2);

            context.MemberName = "DefaultLevel";
            context.DisplayName = "CollectLogsOptions.DefaultLevel";
            validationAttributes.Add(__Attributes.A9);
            if (!Validator.TryValidateValue(options.DefaultLevel, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "Duration";
            context.DisplayName = "CollectLogsOptions.Duration";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A8);
            if (!Validator.TryValidateValue(options.Duration, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "Egress";
            context.DisplayName = "CollectLogsOptions.Egress";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A6);
            validationAttributes.Add(__Attributes.A7);
            if (!Validator.TryValidateValue(options.Egress, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "Format";
            context.DisplayName = "CollectLogsOptions.Format";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A10);
            if (!Validator.TryValidateValue(options.Format, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "Validate";
            context.DisplayName = "CollectLogsOptions.Validate";
            (builder ??= new()).AddResults(((IValidatableObject)options).Validate(context));

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions
{
    partial class CollectStacksActionDescriptor
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public ValidateOptionsResult Validate(string? name, CollectStacksOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "CollectStacksOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, _serviceProvider, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(2);

            context.MemberName = "Egress";
            context.DisplayName = "CollectStacksOptions.Egress";
            validationAttributes.Add(__Attributes.A6);
            validationAttributes.Add(__Attributes.A7);
            if (!Validator.TryValidateValue(options.Egress, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "Validate";
            context.DisplayName = "CollectStacksOptions.Validate";
            (builder ??= new()).AddResults(((IValidatableObject)options).Validate(context));

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions
{
    partial class CollectTraceActionDescriptor
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public ValidateOptionsResult Validate(string? name, CollectTraceOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "CollectTraceOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, _serviceProvider, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(2);

            context.MemberName = "Profile";
            context.DisplayName = "CollectTraceOptions.Profile";
            validationAttributes.Add(__Attributes.A11);
            if (!Validator.TryValidateValue(options.Profile, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            if (options.Providers is not null)
            {
                var count = 0;
                foreach (var o in options.Providers)
                {
                    if (o is not null)
                    {
                        (builder ??= new()).AddResult(__EventPipeProviderValidator__.Validate(string.IsNullOrEmpty(name) ? $"CollectTraceOptions.Providers[{count}]" : $"{name}.Providers[{count}]", o));
                    }
                    else
                    {
                        (builder ??= new()).AddError(string.IsNullOrEmpty(name) ? $"CollectTraceOptions.Providers[{count}] is null" : $"{name}.Providers[{count}] is null");
                    }
                    count++;
                }
            }

            context.MemberName = "BufferSizeMegabytes";
            context.DisplayName = "CollectTraceOptions.BufferSizeMegabytes";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A12);
            if (!Validator.TryValidateValue(options.BufferSizeMegabytes, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "Duration";
            context.DisplayName = "CollectTraceOptions.Duration";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A8);
            if (!Validator.TryValidateValue(options.Duration, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "Egress";
            context.DisplayName = "CollectTraceOptions.Egress";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A6);
            validationAttributes.Add(__Attributes.A7);
            if (!Validator.TryValidateValue(options.Egress, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            if (options.StoppingEvent is not null)
            {
                (builder ??= new()).AddResult(__TraceEventFilterValidator__.Validate(string.IsNullOrEmpty(name) ? "CollectTraceOptions.StoppingEvent" : $"{name}.StoppingEvent", options.StoppingEvent));
            }

            context.MemberName = "Validate";
            context.DisplayName = "CollectTraceOptions.Validate";
            (builder ??= new()).AddResults(((IValidatableObject)options).Validate(context));

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions
{
    partial class ExecuteActionDescriptor
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public ValidateOptionsResult Validate(string? name, ExecuteOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "ExecuteOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, null, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(1);

            context.MemberName = "Path";
            context.DisplayName = "ExecuteOptions.Path";
            validationAttributes.Add(__Attributes.A1);
            if (!Validator.TryValidateValue(options.Path, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions
{
    partial class GetEnvironmentVariableActionDescriptor
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public ValidateOptionsResult Validate(string? name, GetEnvironmentVariableOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "GetEnvironmentVariableOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, null, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(1);

            context.MemberName = "Name";
            context.DisplayName = "GetEnvironmentVariableOptions.Name";
            validationAttributes.Add(__Attributes.A1);
            if (!Validator.TryValidateValue(options.Name, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions
{
    partial class LoadProfilerActionDescriptor
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public ValidateOptionsResult Validate(string? name, LoadProfilerOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "LoadProfilerOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, null, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(2);

            context.MemberName = "Path";
            context.DisplayName = "LoadProfilerOptions.Path";
            validationAttributes.Add(__Attributes.A1);
            if (!Validator.TryValidateValue(options.Path, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "Clsid";
            context.DisplayName = "LoadProfilerOptions.Clsid";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A1);
            validationAttributes.Add(__Attributes.A13);
            if (!Validator.TryValidateValue(options.Clsid, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Actions
{
    partial class SetEnvironmentVariableActionDescriptor
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public ValidateOptionsResult Validate(string? name, SetEnvironmentVariableOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "SetEnvironmentVariableOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, null, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(1);

            context.MemberName = "Name";
            context.DisplayName = "SetEnvironmentVariableOptions.Name";
            validationAttributes.Add(__Attributes.A1);
            if (!Validator.TryValidateValue(options.Name, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options
{
    internal sealed partial class __CollectionRuleLimitsOptionsValidator__
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public static ValidateOptionsResult Validate(string? name, CollectionRuleLimitsOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "CollectionRuleLimitsOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, null, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(1);

            context.MemberName = "ActionCount";
            context.DisplayName = "CollectionRuleLimitsOptions.ActionCount";
            validationAttributes.Add(__Attributes.A14);
            if (!Validator.TryValidateValue(options.ActionCount, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "ActionCountSlidingWindowDuration";
            context.DisplayName = "CollectionRuleLimitsOptions.ActionCountSlidingWindowDuration";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A8);
            if (!Validator.TryValidateValue(options.ActionCountSlidingWindowDuration, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "RuleDuration";
            context.DisplayName = "CollectionRuleLimitsOptions.RuleDuration";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A15);
            if (!Validator.TryValidateValue(options.RuleDuration, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options.Actions
{
    internal sealed partial class __TraceEventFilterValidator__
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public static ValidateOptionsResult Validate(string? name, TraceEventFilter options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "TraceEventFilter.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, null, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(1);

            context.MemberName = "ProviderName";
            context.DisplayName = "TraceEventFilter.ProviderName";
            validationAttributes.Add(__Attributes.A1);
            if (!Validator.TryValidateValue(options.ProviderName, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "EventName";
            context.DisplayName = "TraceEventFilter.EventName";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A1);
            if (!Validator.TryValidateValue(options.EventName, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options
{
    partial class CollectionRuleActionOptionsValidator
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public ValidateOptionsResult Validate(string? name, CollectionRuleActionOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "CollectionRuleActionOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, _serviceProvider, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(1);

            context.MemberName = "Type";
            context.DisplayName = "CollectionRuleActionOptions.Type";
            validationAttributes.Add(__Attributes.A1);
            if (!Validator.TryValidateValue(options.Type, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "Validate";
            context.DisplayName = "CollectionRuleActionOptions.Validate";
            (builder ??= new()).AddResults(((IValidatableObject)options).Validate(context));

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options
{
    partial class CollectionRuleTriggerOptionsValidator
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public ValidateOptionsResult Validate(string? name, CollectionRuleTriggerOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "CollectionRuleTriggerOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, _serviceProvider, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(1);

            context.MemberName = "Type";
            context.DisplayName = "CollectionRuleTriggerOptions.Type";
            validationAttributes.Add(__Attributes.A1);
            if (!Validator.TryValidateValue(options.Type, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "Validate";
            context.DisplayName = "CollectionRuleTriggerOptions.Validate";
            (builder ??= new()).AddResults(((IValidatableObject)options).Validate(context));

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Options.Triggers
{
    partial class EventCounterOptions
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public static ValidateOptionsResult Validate(string? name, EventCounterOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "EventCounterOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, null, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(1);

            context.MemberName = "ProviderName";
            context.DisplayName = "EventCounterOptions.ProviderName";
            validationAttributes.Add(__Attributes.A1);
            if (!Validator.TryValidateValue(options.ProviderName, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "CounterName";
            context.DisplayName = "EventCounterOptions.CounterName";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A1);
            if (!Validator.TryValidateValue(options.CounterName, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "SlidingWindowDuration";
            context.DisplayName = "EventCounterOptions.SlidingWindowDuration";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A8);
            if (!Validator.TryValidateValue(options.SlidingWindowDuration, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "Validate";
            context.DisplayName = "EventCounterOptions.Validate";
            (builder ??= new()).AddResults(((IValidatableObject)options).Validate(context));

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Triggers
{
    partial class AspNetRequestCountTriggerDescriptor
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public ValidateOptionsResult Validate(string? name, AspNetRequestCountOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "AspNetRequestCountOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, null, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(2);

            context.MemberName = "RequestCount";
            context.DisplayName = "AspNetRequestCountOptions.RequestCount";
            validationAttributes.Add(__Attributes.A16);
            validationAttributes.Add(__Attributes.A14);
            if (!Validator.TryValidateValue(options.RequestCount, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "SlidingWindowDuration";
            context.DisplayName = "AspNetRequestCountOptions.SlidingWindowDuration";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A8);
            if (!Validator.TryValidateValue(options.SlidingWindowDuration, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Triggers
{
    partial class AspNetRequestDurationTriggerDescriptor
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public ValidateOptionsResult Validate(string? name, AspNetRequestDurationOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "AspNetRequestDurationOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, null, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(2);

            context.MemberName = "RequestCount";
            context.DisplayName = "AspNetRequestDurationOptions.RequestCount";
            validationAttributes.Add(__Attributes.A16);
            validationAttributes.Add(__Attributes.A14);
            if (!Validator.TryValidateValue(options.RequestCount, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "RequestDuration";
            context.DisplayName = "AspNetRequestDurationOptions.RequestDuration";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A17);
            if (!Validator.TryValidateValue(options.RequestDuration, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "SlidingWindowDuration";
            context.DisplayName = "AspNetRequestDurationOptions.SlidingWindowDuration";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A8);
            if (!Validator.TryValidateValue(options.SlidingWindowDuration, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Triggers
{
    partial class AspNetResponseStatusTriggerDescriptor
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public ValidateOptionsResult Validate(string? name, AspNetResponseStatusOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "AspNetResponseStatusOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, null, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(3);

            context.MemberName = "StatusCodes";
            context.DisplayName = "AspNetResponseStatusOptions.StatusCodes";
            validationAttributes.Add(__Attributes.A1);
            validationAttributes.Add(__Attributes.A2);
            validationAttributes.Add(__Attributes.A18);
            if (!Validator.TryValidateValue(options.StatusCodes, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "ResponseCount";
            context.DisplayName = "AspNetResponseStatusOptions.ResponseCount";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A19);
            validationAttributes.Add(__Attributes.A14);
            if (!Validator.TryValidateValue(options.ResponseCount, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "SlidingWindowDuration";
            context.DisplayName = "AspNetResponseStatusOptions.SlidingWindowDuration";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A8);
            if (!Validator.TryValidateValue(options.SlidingWindowDuration, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Triggers
{
    partial class CPUUsageTriggerDescriptor
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public ValidateOptionsResult Validate(string? name, CPUUsageOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "CPUUsageOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, null, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(1);

            context.MemberName = "GreaterThan";
            context.DisplayName = "CPUUsageOptions.GreaterThan";
            validationAttributes.Add(__Attributes.A20);
            if (!Validator.TryValidateValue(options.GreaterThan, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "LessThan";
            context.DisplayName = "CPUUsageOptions.LessThan";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A20);
            if (!Validator.TryValidateValue(options.LessThan, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "SlidingWindowDuration";
            context.DisplayName = "CPUUsageOptions.SlidingWindowDuration";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A8);
            if (!Validator.TryValidateValue(options.SlidingWindowDuration, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "Validate";
            context.DisplayName = "CPUUsageOptions.Validate";
            (builder ??= new()).AddResults(((IValidatableObject)options).Validate(context));

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Triggers
{
    partial class EventCounterTriggerDescriptor
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public ValidateOptionsResult Validate(string? name, EventCounterOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "EventCounterOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, null, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(1);

            context.MemberName = "ProviderName";
            context.DisplayName = "EventCounterOptions.ProviderName";
            validationAttributes.Add(__Attributes.A1);
            if (!Validator.TryValidateValue(options.ProviderName, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "CounterName";
            context.DisplayName = "EventCounterOptions.CounterName";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A1);
            if (!Validator.TryValidateValue(options.CounterName, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "SlidingWindowDuration";
            context.DisplayName = "EventCounterOptions.SlidingWindowDuration";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A8);
            if (!Validator.TryValidateValue(options.SlidingWindowDuration, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "Validate";
            context.DisplayName = "EventCounterOptions.Validate";
            (builder ??= new()).AddResults(((IValidatableObject)options).Validate(context));

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Triggers
{
    partial class EventMeterTriggerDescriptor
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public ValidateOptionsResult Validate(string? name, EventMeterOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "EventMeterOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, null, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(1);

            context.MemberName = "MeterName";
            context.DisplayName = "EventMeterOptions.MeterName";
            validationAttributes.Add(__Attributes.A1);
            if (!Validator.TryValidateValue(options.MeterName, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "InstrumentName";
            context.DisplayName = "EventMeterOptions.InstrumentName";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A1);
            if (!Validator.TryValidateValue(options.InstrumentName, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "SlidingWindowDuration";
            context.DisplayName = "EventMeterOptions.SlidingWindowDuration";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A8);
            if (!Validator.TryValidateValue(options.SlidingWindowDuration, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "HistogramPercentile";
            context.DisplayName = "EventMeterOptions.HistogramPercentile";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A20);
            if (!Validator.TryValidateValue(options.HistogramPercentile, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "Validate";
            context.DisplayName = "EventMeterOptions.Validate";
            (builder ??= new()).AddResults(((IValidatableObject)options).Validate(context));

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Triggers
{
    partial class GCHeapSizeTriggerDescriptor
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public ValidateOptionsResult Validate(string? name, GCHeapSizeOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "GCHeapSizeOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, null, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(1);

            context.MemberName = "GreaterThan";
            context.DisplayName = "GCHeapSizeOptions.GreaterThan";
            validationAttributes.Add(__Attributes.A21);
            if (!Validator.TryValidateValue(options.GreaterThan, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "LessThan";
            context.DisplayName = "GCHeapSizeOptions.LessThan";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A21);
            if (!Validator.TryValidateValue(options.LessThan, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "SlidingWindowDuration";
            context.DisplayName = "GCHeapSizeOptions.SlidingWindowDuration";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A8);
            if (!Validator.TryValidateValue(options.SlidingWindowDuration, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "Validate";
            context.DisplayName = "GCHeapSizeOptions.Validate";
            (builder ??= new()).AddResults(((IValidatableObject)options).Validate(context));

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace Microsoft.Diagnostics.Tools.Monitor.CollectionRules.Triggers
{
    partial class ThreadpoolQueueLengthTriggerDescriptor
    {
        /// <summary>
        /// Validates a specific named options instance (or all when <paramref name="name"/> is <see langword="null" />).
        /// </summary>
        /// <param name="name">The name of the options instance being validated.</param>
        /// <param name="options">The options instance.</param>
        /// <returns>Validation result.</returns>
        public ValidateOptionsResult Validate(string? name, ThreadpoolQueueLengthOptions options)
        {
            ValidateOptionsResultBuilder? builder = null;
            string displayName = string.IsNullOrEmpty(name) ? "ThreadpoolQueueLengthOptions.Validate" : $"{name}.Validate";
            var context = new ValidationContext(options, displayName, null, null);
            var validationResults = new List<ValidationResult>();
            var validationAttributes = new List<ValidationAttribute>(1);

            context.MemberName = "GreaterThan";
            context.DisplayName = "ThreadpoolQueueLengthOptions.GreaterThan";
            validationAttributes.Add(__Attributes.A21);
            if (!Validator.TryValidateValue(options.GreaterThan, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "LessThan";
            context.DisplayName = "ThreadpoolQueueLengthOptions.LessThan";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A21);
            if (!Validator.TryValidateValue(options.LessThan, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "SlidingWindowDuration";
            context.DisplayName = "ThreadpoolQueueLengthOptions.SlidingWindowDuration";
            validationResults.Clear();
            validationAttributes.Clear();
            validationAttributes.Add(__Attributes.A8);
            if (!Validator.TryValidateValue(options.SlidingWindowDuration, context, validationResults, validationAttributes))
            {
                (builder ??= new()).AddResults(validationResults);
            }

            context.MemberName = "Validate";
            context.DisplayName = "ThreadpoolQueueLengthOptions.Validate";
            (builder ??= new()).AddResults(((IValidatableObject)options).Validate(context));

            return builder is null ? ValidateOptionsResult.Success : builder.Build();
        }
    }
}
namespace __OptionValidationStaticInstances
{
    static file class __Attributes
    {
        internal static readonly RequiredAttribute A1 = new RequiredAttribute();

        internal static readonly __OptionValidationGeneratedAttributes.__SourceGen__MinLengthAttribute A2 = new __OptionValidationGeneratedAttributes.__SourceGen__MinLengthAttribute(
            (int)1);

        internal static readonly IntegerOrHexStringAttribute A3 = new IntegerOrHexStringAttribute();

        internal static readonly EnumDataTypeAttribute A4 = new EnumDataTypeAttribute(
            typeof(EventLevel));

        internal static readonly EnumDataTypeAttribute A5 = new EnumDataTypeAttribute(
            typeof(DumpType));

        internal static readonly RequiredAttribute A6 = new RequiredAttribute()
        {
            ErrorMessageResourceName = "ErrorMessage_NoDefaultEgressProvider",
            ErrorMessageResourceType = typeof(OptionsDisplayStrings)
        };

        internal static readonly ValidateEgressProviderAttribute A7 = new ValidateEgressProviderAttribute();

        internal static readonly __OptionValidationGeneratedAttributes.__SourceGen__RangeAttribute A8 = new __OptionValidationGeneratedAttributes.__SourceGen__RangeAttribute(
            typeof(TimeSpan),
            "00:00:01",
            "1.00:00:00");

        internal static readonly EnumDataTypeAttribute A9 = new EnumDataTypeAttribute(
            typeof(LogLevel));

        internal static readonly EnumDataTypeAttribute A10 = new EnumDataTypeAttribute(
            typeof(LogFormat));

        internal static readonly EnumDataTypeAttribute A11 = new EnumDataTypeAttribute(
            typeof(TraceProfile));

        internal static readonly __OptionValidationGeneratedAttributes.__SourceGen__RangeAttribute A12 = new __OptionValidationGeneratedAttributes.__SourceGen__RangeAttribute(
            (int)1,
            (int)1024);

        internal static readonly RequiredGuidAttribute A13 = new RequiredGuidAttribute();

        internal static readonly __OptionValidationGeneratedAttributes.__SourceGen__RangeAttribute A14 = new __OptionValidationGeneratedAttributes.__SourceGen__RangeAttribute(
            (int)1,
            (int)2147483647);

        internal static readonly __OptionValidationGeneratedAttributes.__SourceGen__RangeAttribute A15 = new __OptionValidationGeneratedAttributes.__SourceGen__RangeAttribute(
            typeof(TimeSpan),
            "00:00:01",
            "365.00:00:00");

        internal static readonly RequiredAttribute A16 = new RequiredAttribute()
        {
            ErrorMessageResourceName = "ErrorMessage_NoDefaultRequestCount",
            ErrorMessageResourceType = typeof(OptionsDisplayStrings)
        };

        internal static readonly __OptionValidationGeneratedAttributes.__SourceGen__RangeAttribute A17 = new __OptionValidationGeneratedAttributes.__SourceGen__RangeAttribute(
            typeof(TimeSpan),
            "00:00:00",
            "01:00:00");

        internal static readonly RegularExpressionsAttribute A18 = new RegularExpressionsAttribute(
            "[1-5][0-9]{2}(-[1-5][0-9]{2})?")
        {
            ErrorMessageResourceName = "ErrorMessage_StatusCodesRegularExpressionDoesNotMatch",
            ErrorMessageResourceType = typeof(OptionsDisplayStrings)
        };

        internal static readonly RequiredAttribute A19 = new RequiredAttribute()
        {
            ErrorMessageResourceName = "ErrorMessage_NoDefaultResponseCount",
            ErrorMessageResourceType = typeof(OptionsDisplayStrings)
        };

        internal static readonly __OptionValidationGeneratedAttributes.__SourceGen__RangeAttribute A20 = new __OptionValidationGeneratedAttributes.__SourceGen__RangeAttribute(
            (double)0,
            (double)100);

        internal static readonly __OptionValidationGeneratedAttributes.__SourceGen__RangeAttribute A21 = new __OptionValidationGeneratedAttributes.__SourceGen__RangeAttribute(
            (double)0,
            (double)1.7976931348623157E+308);
    }
}
namespace __OptionValidationStaticInstances
{
    static class __Validators
    {
    }
}
namespace __OptionValidationGeneratedAttributes
{
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
    file class __SourceGen__MinLengthAttribute : ValidationAttribute
    {
        private static string DefaultErrorMessageString => "The field {0} must be a string or array type with a minimum length of '{1}'.";

        public __SourceGen__MinLengthAttribute(int length) : base(() => DefaultErrorMessageString) { Length = length; }
        public int Length { get; }
        public override bool IsValid(object? value)
        {
            if (Length < -1)
            {
                throw new InvalidOperationException("MinLengthAttribute must have a Length value that is zero or greater.");
            }
            if (value == null)
            {
                return true;
            }

            int length;
            if (value is string stringValue)
            {
                length = stringValue.Length;
            }
            else if (value is ICollection collectionValue)
            {
                length = collectionValue.Count;
            }
            else
            {
                throw new InvalidCastException($"The field of type {value.GetType()} must be a string, array, or ICollection type.");
            }

            return length >= Length;
        }
        public override string FormatErrorMessage(string name) => string.Format(CultureInfo.CurrentCulture, ErrorMessageString, name, Length);
    }

    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
    file class __SourceGen__RangeAttribute : ValidationAttribute
    {
        public __SourceGen__RangeAttribute(int minimum, int maximum) : base()
        {
            Minimum = minimum;
            Maximum = maximum;
            OperandType = typeof(int);
        }
        public __SourceGen__RangeAttribute(double minimum, double maximum) : base()
        {
            Minimum = minimum;
            Maximum = maximum;
            OperandType = typeof(double);
        }
        public __SourceGen__RangeAttribute(Type type, string minimum, string maximum) : base()
        {
            OperandType = type;
            _needToConvertMinMax = true;
            Minimum = minimum;
            Maximum = maximum;
        }
        public object Minimum { get; private set; }
        public object Maximum { get; private set; }
        public bool MinimumIsExclusive { get; set; }
        public bool MaximumIsExclusive { get; set; }
        public Type OperandType { get; }
        public bool ParseLimitsInInvariantCulture { get; set; }
        public bool ConvertValueInInvariantCulture { get; set; }
        public override string FormatErrorMessage(string name) =>
                string.Format(CultureInfo.CurrentCulture, GetValidationErrorMessage(), name, Minimum, Maximum);
        private readonly bool _needToConvertMinMax;
        private volatile bool _initialized;
        private readonly object _lock = new();
        private const string MinMaxError = "The minimum and maximum values must be set to valid values.";

        public override bool IsValid(object? value)
        {
            if (!_initialized)
            {
                lock (_lock)
                {
                    if (!_initialized)
                    {
                        if (Minimum is null || Maximum is null)
                        {
                            throw new InvalidOperationException(MinMaxError);
                        }
                        if (_needToConvertMinMax)
                        {
                            CultureInfo culture = ParseLimitsInInvariantCulture ? CultureInfo.InvariantCulture : CultureInfo.CurrentCulture;
                            if (OperandType == typeof(TimeSpan))
                            {
                                if (!TimeSpan.TryParse((string)Minimum, culture, out TimeSpan timeSpanMinimum) ||
                                    !TimeSpan.TryParse((string)Maximum, culture, out TimeSpan timeSpanMaximum))
                                {
                                    throw new InvalidOperationException(MinMaxError);
                                }
                                Minimum = timeSpanMinimum;
                                Maximum = timeSpanMaximum;
                            }
                            else
                            {
                                Minimum = ConvertValue(Minimum, culture) ?? throw new InvalidOperationException(MinMaxError);
                                Maximum = ConvertValue(Maximum, culture) ?? throw new InvalidOperationException(MinMaxError);
                            }
                        }
                        int cmp = ((IComparable)Minimum).CompareTo((IComparable)Maximum);
                        if (cmp > 0)
                        {
                            throw new InvalidOperationException("The maximum value '{Maximum}' must be greater than or equal to the minimum value '{Minimum}'.");
                        }
                        else if (cmp == 0 && (MinimumIsExclusive || MaximumIsExclusive))
                        {
                            throw new InvalidOperationException("Cannot use exclusive bounds when the maximum value is equal to the minimum value.");
                        }
                        _initialized = true;
                    }
                }
            }

            if (value is null or string { Length: 0 })
            {
                return true;
            }

            CultureInfo formatProvider = ConvertValueInInvariantCulture ? CultureInfo.InvariantCulture : CultureInfo.CurrentCulture;
            object? convertedValue;

            if (OperandType == typeof(TimeSpan))
            {
                if (value is TimeSpan)
                {
                    convertedValue = value;
                }
                else if (value is string)
                {
                    if (!TimeSpan.TryParse((string)value, formatProvider, out TimeSpan timeSpanValue))
                    {
                        return false;
                    }
                    convertedValue = timeSpanValue;
                }
                else
                {
                    throw new InvalidOperationException($"A value type {value.GetType()} that is not a TimeSpan or a string has been given. This might indicate a problem with the source generator.");
                }
            }
            else
            {
                try
                {
                    convertedValue = ConvertValue(value, formatProvider);
                }
                catch (Exception e) when (e is FormatException or InvalidCastException or NotSupportedException)
                {
                    return false;
                }
            }

            var min = (IComparable)Minimum;
            var max = (IComparable)Maximum;

            return
                (MinimumIsExclusive ? min.CompareTo(convertedValue) < 0 : min.CompareTo(convertedValue) <= 0) &&
                (MaximumIsExclusive ? max.CompareTo(convertedValue) > 0 : max.CompareTo(convertedValue) >= 0);
        }
        private string GetValidationErrorMessage()
        {
            return (MinimumIsExclusive, MaximumIsExclusive) switch
            {
                (false, false) => "The field {0} must be between {1} and {2}.",
                (true, false) => "The field {0} must be between {1} exclusive and {2}.",
                (false, true) => "The field {0} must be between {1} and {2} exclusive.",
                (true, true) => "The field {0} must be between {1} exclusive and {2} exclusive.",
            };
        }
        private object? ConvertValue(object? value, CultureInfo formatProvider)
        {
            if (value is string stringValue)
            {
                value = Convert.ChangeType(stringValue, OperandType, formatProvider);
            }
            else
            {
                value = Convert.ChangeType(value, OperandType, formatProvider);
            }
            return value;
        }
    }
}
