name: 'Create Learning Path Update'
run-name: '[${{ github.ref_name }}] Create Learning Path Update'

on:
  workflow_dispatch:
    inputs:
      baselineTag:
        description: 'Baseline Release Tag Override'
        required: false
        type: string

  # workflow_run:
  #   workflows: ["Scan For Learning Path Update Comments"]
  #   types:
  #     - completed

permissions: {}

jobs:
  create-learning-path-update-pr:
    name: 'Create Learning Path Update'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout main
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          persist-credentials: true # We need to persist credentials to push the resulting changes upstream.
          ref: main

      - name: Get previous update SHA
        id: get_sha
        run: |
          cd .github
          prev_sha=$(cat learning-path-sha.txt)
          echo "prev_sha=$prev_sha" >> $GITHUB_ENV
          echo "Writing prev_sha into GitHub Env: $prev_sha"
          cd ../

      - name: Update Learning Path Hashes
        id: update-links
        uses: kkeirstead/UpdateLearningPathCommitHashes@main
        with:
          learningPathsDirectory: 'documentation/learningPath'
          learningPathHashFile: '.github/learning-path-sha.txt'
          oldHash: ${{ env.prev_sha }}
          newHash: "abc"

      - name: Open PR
        uses: ./.github/actions/open-pr
        with:
          files_to_commit: ${{ steps.update-links.outputs.modifiedFiles }}
          title: "Update Learning Path Links"
          commit_message: Update Learning Path Links
          body: This PR was auto generated and will not be automatically merged in - adjustments should be made manually as-needed.
          branch_name: learningPathUpdates/${{ env.prev_sha }} # should probably update this to new sha once we determine that
          fail_if_files_unchanged: true
          auth_token: ${{ secrets.GITHUB_TOKEN }}
