name: Respond To First Issue
on:
  issues:
    types:
      - opened

permissions: {}

jobs:
  check-if-new-user:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/first-interaction@753c925c8d1ac6fede23781875376600628d9b5d
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "## Welcome to dotnet-monitor!\nThanks for creating your first issue; let us know what you think of dotnet-monitor by filling out our [survey](https://aka.ms/dotnet-monitor-survey?src=firstissue)."
