name: 'Spellcheck'
on:
  pull_request:
    paths: ['src/**', '**/*.md']

permissions:
  pull-requests: read

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - uses: streetsidesoftware/cspell-action@e0668cf020899e887ee8ad4d173c31738a79eae8
        name: Documentation spellcheck
        if: ${{ !cancelled() }}
        with:
            files: '**/*.md'
            inline: error
            incremental_files_only: true

      - uses: streetsidesoftware/cspell-action@e0668cf020899e887ee8ad4d173c31738a79eae8
        name: Resx spellcheck
        if: ${{ !cancelled() }}
        with:
            files: 'src/**/*.resx'
            inline: error
            incremental_files_only: true

      - uses: streetsidesoftware/cspell-action@e0668cf020899e887ee8ad4d173c31738a79eae8
        name: Source code spellcheck
        if: ${{ !cancelled() }}
        with:
            files: 'src/**/*{.cs,.cpp,.h,.targets,.props,.*proj}'
            inline: warning
            incremental_files_only: true
            # Do not cause the gate to fail if potential typos in source code are found.
            # The signal-to-noise ratio here needs to be better understood first.
            strict: false
