name: 'Submit Learning Paths Staleness Check'

on:
  workflow_run:
    workflows: ["Check Learning Path Links"]
    types:
      - completed

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:  
  submit-learning-paths-staleness-check:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
        id: check-user
        with:
          script: |
            await github.rest.repos.checkCollaborator({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: context.payload.workflow_run.triggering_actor.login
            });

      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          persist-credentials: true

      # Download the artifact from the workflow that kicked off this one.
      # The default artifact download action doesn't support cross-workflow
      # artifacts, so use a 3rd party one.
      - name: 'Download linting results'
        uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615
        with:
          workflow: ${{env.workflow_name}}
          run_id: ${{github.event.workflow_run.id }}
          name: learning-path-review
          path: ./learning-path-review

      - name: Set Env Vars
        run: |
          modifiedFiles=$(cat ./learning-path-review/modifiedFiles)
          manuallyReview=$(cat ./learning-path-review/manuallyReview)
          suggestions=$(cat ./learning-path-review/suggestions)
          echo "modifiedFiles=$modifiedFiles" >> $GITHUB_ENV
          echo "manuallyReview=$manuallyReview" >> $GITHUB_ENV
          echo "suggestions=$suggestions" >> $GITHUB_ENV

      - uses: actions/github-script@v6
        name: Check For Duplicate Comment
        if: ${{ env.modifiedFiles != '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODIFIED_FILES: ${{ env.modifiedFiles }}
          MANUALLY_REVIEW: ${{ env.manuallyReview }}
          SUGGESTIONS: ${{ env.suggestions }}
        with:
          script: |
            modifiedFiles = process.env.MODIFIED_FILES;
            manuallyReview = process.env.MANUALLY_REVIEW;
            suggestions = process.env.SUGGESTIONS;
            comment_body = "### Learning Paths Staleness Check \n\n #### Impacted Paths:\n\n" + modifiedFiles.replaceAll(",", "\n") + "\n\n---------\n\n #### Manually Review:\n\n" + manuallyReview.replaceAll(",", "\n") + "\n\n---------\n\n #### Suggestions:\n\n" + suggestions.replaceAll(",", "\n");
          
            const comments = await github.rest.issues.listComments({
              issue_number: context.payload.workflow_run.pull_requests[0].number,
              owner: context.repo.owner,
              repo: context.repo.repo
            })

            var commentExists = false;

            console.log("Actual comment body:");
            console.log(comment_body);
            console.log("");
            
            for (const comment of comments.data) {
              console.log(comment.body);
              if (comment.body == comment_body) {
                commentExists = true;
              }
            }

            if (!commentExists)
            {
              github.rest.issues.createComment({
                issue_number: context.payload.workflow_run.pull_requests[0].number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment_body
              })
            }
